# Generated by Django 5.2 on 2025-04-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='agua',
            field=models.IntegerField(default=8, help_text='Copos de água por dia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='atividade_fisica',
            field=models.CharField(default='nunca', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='preferencias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='refeicoes_por_dia',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='questionario',
            name='sono',
            field=models.IntegerField(default='8', help_text='Horas de sono por noite'),
            preserve_default=False,
        ),
    ]