# Generated by Django 5.2 on 2025-04-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_questionario_agua_questionario_atividade_fisica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='preferencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='tem_restricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
