# Generated by Django 5.2 on 2025-04-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0003_alter_questionario_preferencias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='preferencias',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='tem_restricao',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='user',
        ),
        migrations.AddField(
            model_name='questionario',
            name='estresse',
            field=models.CharField(default='Moderado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='fome',
            field=models.CharField(default='moderada', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='genero',
            field=models.CharField(default='não informado', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='idade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='nome',
            field=models.CharField(default='Usuário', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='objetivo',
            field=models.CharField(default='manter', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='preferencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='restricoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='usa_suplementos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='agua',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='refeicoes_por_dia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='sono',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PerfilNutricional',
        ),
    ]