# Generated by Django 5.2 on 2025-04-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0004_remove_questionario_preferencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='agua',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='atividade_fisica',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='estresse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='fome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='genero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='refeicoes_por_dia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='sono',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]