# Generated by Django 5.2 on 2025-04-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0006_questionario_altura_questionario_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='agua_bebida',
            field=models.FloatField(default=0),
        ),
    ]
