# Generated by Django 5.2 on 2025-04-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0007_questionario_agua_bebida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]