# Generated by Django 5.2 on 2025-04-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0008_alter_questionario_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('valor_nutricional', models.TextField(blank=True)),
                ('vegetariano', models.BooleanField(default=False)),
                ('sem_lactose', models.BooleanField(default=False)),
                ('sem_gluten', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(blank=True)),
                ('alimento_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas_para', to='meu_app.alimento')),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitui', to='meu_app.alimento')),
            ],
        ),
    ]
