# Generated by Django 5.2 on 2025-04-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0010_cardapio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='agua_bebida',
            field=models.FloatField(default=0, null=True),
        ),
    ]
