# Generated by Django 5.2 on 2025-04-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0010_cardapio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='calorias',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimento',
            name='carboidratos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimento',
            name='gorduras',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimento',
            name='proteinas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='valor_nutricional',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
