# Generated by Django 5.2 on 2025-04-22 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0010_cardapio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='itens',
        ),
        migrations.AddField(
            model_name='alimento',
            name='calorias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='carboidratos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='gorduras',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='proteinas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('categoria', models.CharField(max_length=100)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.alimento')),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.cardapio')),
            ],
        ),
        migrations.AddField(
            model_name='cardapio',
            name='alimentos',
            field=models.ManyToManyField(through='meu_app.ItemCardapio', to='meu_app.alimento'),
        ),
    ]
