# Generated by Django 5.2 on 2025-04-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0011_remove_cardapio_itens_alimento_calorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='alimentos',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='calorias',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='carboidratos',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='gorduras',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='proteinas',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='itens',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemCardapio',
        ),
    ]
