# Generated by Django 5.2 on 2025-04-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0014_remove_questionario_agua_alter_questionario_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='agua',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
