# Generated by Django 5.2 on 2025-04-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0015_questionario_agua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='agua',
        ),
        migrations.AddField(
            model_name='perfil',
            name='agua_bebida',
            field=models.FloatField(default=0, null=True),
        ),
    ]
