# Generated by Django 5.2 on 2025-04-23 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0016_remove_questionario_agua_perfil_agua_bebida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='agua_bebida',
        ),
        migrations.AddField(
            model_name='questionario',
            name='agua',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
