# Generated by Django 5.2 on 2025-04-23 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0017_remove_perfil_agua_bebida_questionario_agua_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='agua',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
