# Generated by Django 5.2 on 2025-04-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0018_alter_questionario_agua_alter_questionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='agua_bebida',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
