# Generated by Django 5.2 on 2025-04-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0019_alter_questionario_agua_bebida'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='questionario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='meu_app.questionario'),
        ),
    ]
