# Generated by Django 5.2 on 2025-04-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0020_perfil_questionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='agua',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='atividade_fisica',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='fome',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='sono',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='objetivo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
