# Generated by Django 5.2 on 2025-04-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0022_perfil_data_nascimento_perfil_endereco_perfil_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='atividade_fisica',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questionario',
            name='fome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questionario',
            name='genero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questionario',
            name='sono',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
