# Generated by Django 5.2 on 2025-04-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0024_rename_agua_bebida_questionario_agua'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionario',
            old_name='agua',
            new_name='agua_bebida',
        ),
        migrations.AlterField(
            model_name='questionario',
            name='atividade_fisica',
            field=models.CharField(blank=True, choices=[('Sedentario', 'Sedentário'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Intensa', 'Intensa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='fome',
            field=models.CharField(blank=True, choices=[('Baixa', 'Baixa'), ('Moderada', 'Moderada'), ('Alta', 'Alta')], max_length=100),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='sono',
            field=models.CharField(blank=True, choices=[('Ruim', 'Ruim'), ('Moderado', 'Moderado'), ('Bom', 'Bom')], max_length=100),
        ),
    ]
