# Generated by Django 5.2 on 2025-04-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0025_rename_agua_questionario_agua_bebida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
