# Generated by Django 5.2 on 2025-04-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0026_cardapio_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='agua_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
