# Generated by Django 5.2 on 2025-04-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0027_alter_perfil_altura_alter_perfil_peso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='agua_bebida',
        ),
    ]
