# Generated by Django 5.2 on 2025-04-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0028_remove_questionario_agua_bebida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='peso',
        ),
    ]
