# Generated by Django 5.2 on 2025-04-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0029_remove_questionario_altura_remove_questionario_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='genero',
        ),
    ]
