# Generated by Django 5.2 on 2025-05-14 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0030_remove_perfil_altura_remove_perfil_endereco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('peso_atual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso Atual (kg)')),
                ('meta_peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Meta de Peso (kg)')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Peso',
                'verbose_name_plural': 'Registros de Peso',
                'ordering': ['-data'],
            },
        ),
    ]
