# Generated by Django 5.2 on 2025-05-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0031_registropeso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registropeso',
            options={'ordering': ['-data'], 'verbose_name': 'Registro_de_Peso', 'verbose_name_plural': 'Registro_de_Peso'},
        ),
    ]
