# Generated by Django 5.2 on 2025-05-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0032_alter_registropeso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registropeso',
            options={'ordering': ['-data'], 'verbose_name': 'Registro de Peso', 'verbose_name_plural': 'Registros de Peso'},
        ),
        migrations.AddField(
            model_name='questionario',
            name='ultima_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Última atualização do perfil'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='ultima_modificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Última modificação relevante'),
        ),
    ]
