
name: Build and deploy Python app to Azure Web App - djangodeploy20

on:
  push:
    branches:
      - deploy-novo
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm ci
          cd ..
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC3C986B1912469198C6D4ADB7587DA8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_80BE748A2A1040A59CF946F9BB300979 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0C744D246A4741358E2F00A69A2960F1 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'djangodeploy20'
          slot-name: 'Production'
          
      - name: Cleaning testing files
        run: |
          cd meu_projeto/
          rm -f db.sqlite3
          rm -f .env
          rm cypress.config.js
          rm package-lock.json
          rm package.json
          rm -rf cypress
          rm -rf node_modules
          cd ..
          
      - name: Zip artifact for deployment
        run: |
          cd meu_projeto/
          zip release.zip ./* -r
          cd ..
          mv meu_projeto/release.zip .

      - name: Run local server
        run: |
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run
